version: '3'
services:
  db:
    image: postgres:11
  app: &app_base
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  spring:
    <<: *app_base
    command: bin/spring server
    ports: [ ]
