version: '3.5'
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    environment:
      RAILS_ENV: production
      S3_REGION: hoge
      S3_ACCESS_KEY: FUGA
      S3_SECRET_KEY: foo
      S3_BUCKET: bar
      SECRET_KEY_BASE: AAA
      RAILS_LOG_TO_STDOUT: true
    build:
      dockerfile: ./docker/production/Dockerfile
      context: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
