---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels: 
    component: db
spec:
  containers:
    - name: postgres
      image: postgres:11
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pgdata
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: pvc-db
