---
apiVersion: v1
kind: Pod
metadata:
  name: setup-app
spec:
  containers:
    - image: ghcr.io/ikaruga777/rails-tutorial-sample-app/app:0.2
      name: setup-app
      command:
        - /bin/bash
      args:
        - -c
        - bin/setup
      ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      env:
        - name: RAILS_ENV
          value: production
        - name: DATABASE_URL
          value: postgres://postgres:postgres@db/app
        - name: S3_REGION
          value: hoge
        - name: S3_ACCESS_KEY
          value: FUGA
        - name: S3_SECRET_KEY
          value: foo
        - name: S3_BUCKET
          value: bar
        - name: SECRET_KEY_BASE
          value: AAA
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
  imagePullSecrets:
    - name: ghcr.io
