name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 4
    steps:
    - name: setup dependencies
      run: sudo apt-get update -y && sudo apt-get install -y build-essential libsqlite3-dev libcurl4-openssl-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby 3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec bin/rails test
    - uses: actions/cache@v1.1.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
